### PR TITLE
Fix 127, 128, 177

### LINKED ISSUE #127: Update main.parameters.json
- [ ] Add environment variable for OpenAI resource group location to be used in *main.bicep*. Related to changes in #128

### PR DESCRIPTION
**Pull request by LittleLittleCloud**
## Purpose

* ...

Fix
#127 
#128 
#177 

## Application Insights
image

## Does this introduce a breaking change?

```
[ ] Yes
[ ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

### CODE REVIEW

**Comment by luisquintanilla** [comment]
@LittleLittleCloud I ran into this isuse. 

`{
  "error": {
    "code": "InvalidTemplate",
    "message": "Deployment template validation failed: 'The provided value for the template parameter 'openAiResourceLocation' is not valid. The value '' is not part of the allowed value(s): 'canadaeast,eastus,eastus2,francecentral,switzerlandnorth,uksouth,japaneast,northcentralus'.'.",
    "additionalInfo": [
      {
        "type": "TemplateViolation",
        "info": {
          "lineNumber": 1,
          "linePosition": 1786,
          "path": "properties.template.parameters.openAiResourceLocation.allowedValues"
        }
      }
    ]
  }
}
`

**Comment by LittleLittleCloud** [comment]
Did you run azd down  --purge first?

**Comment by luisquintanilla** [comment]
> Did you run azd down --purge first?

This was on a fresh deployment

**Review by luisquintanilla — APPROVED** [review]
LGTM. Thanks @LittleLittleCloud

**Review by luisquintanilla — APPROVED** [review]
LGTM

**Pull request merged**
